pipeline {
    agent any
     environment {
        QUARTUS_ROOTDIR = '/home/intel-ldra/intelFPGA_pro/24.2/quartus'
        ARM_GNU_TOOLCHAIN = '/home/intel-ldra/Zephyr_ATF_golden_ref_IGN/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf/bin'
        PATH = "${ARM_GNU_TOOLCHAIN}:${QUARTUS_ROOTDIR}/bin:${QUARTUS_ROOTDIR}/linux64:${QUARTUS_ROOTDIR}/../qsys/bin:${env.PATH}"
        WORKSPACE_PATH = "/home/intel-ldra/Jenkins" 
        REPO_PATH = "${WORKSPACE_PATH}/os.rtos.fpga.freertos"
    }
    stages {
        stage('Pre-clone Cleanup') {
            steps {
                script {
                    sh '''
                        if [ -d "${REPO_PATH}" ]; then
                            echo "Repository already exists. Removing it..."
                            rm -rf "${REPO_PATH}"
                        fi
                    '''
                }
            }
        }
        stage('Clone Repository') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: '79ac05c0-51e0-4e78-9d74-fc030bda2bcc', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
                        sh '''
                            git clone --branch release/v0.3.0 https://${GIT_USER}:${GIT_PASS}@github.com/intel-collab/os.rtos.fpga.freertos.git ${REPO_PATH}
                            cd ${REPO_PATH}
                            git submodule update --init --recursive
                        '''
                    }
                }
            }
        }
        
        stage('List Repository Contents') {
            steps {
                script {
                    sh '''
                        cd ${REPO_PATH}
                        ls -R
                    '''
                }
            }
        }
        stage('Build Application') {
            steps {
                script {
                    sh '''
                        cd ${REPO_PATH}
                        make APP=samples clean
                        make APP=samples
                    '''
                }
            }
        }
        stage('Simulate Flashing') {
            steps {
                script {
                    sh '''
                        cd ${WORKSPACE_PATH}/simics
                        ./make_rtos_simics.sh
                    '''
                }
            }
        }
      
        stage('Check Python Version and Installed Packages') {
            steps {
                script {
                    sh '''
                        python3 --version
                        python3 -m pip list
                    '''
                }
            }
        }
        stage('Run Python Script for Boot Log and Test Results') {
            steps {
                script {
                    sh '''
                        cd ${WORKSPACE_PATH}/automation_scripts/sample_tests
                        export PYTHONUSERBASE=$HOME/.local
                        python3 -m pip install --user pyserial  
                        python3 timer_sample_test.py > ${WORKSPACE_PATH}/test_results.txt  
                    '''
                }
            }
        }
        stage('Save Results') {
    steps {
        script {
            sh '''
                echo "Checking for boot_log.txt in ${WORKSPACE_PATH}/simics/deploy/"
                ls -l ${WORKSPACE_PATH}/simics/deploy/

                if [ -f "${WORKSPACE_PATH}/simics/deploy/boot_log.txt" ]; then
                    echo "boot_log.txt found. Copying..."
                    cp "${WORKSPACE_PATH}/simics/deploy/boot_log.txt" "${WORKSPACE_PATH}/"
                else
                    echo "ERROR: boot_log.txt not found!"
                    exit 1
                fi

                echo "Checking if boot_log.txt exists in ${WORKSPACE_PATH}/"
                ls -l ${WORKSPACE_PATH}/
            '''
        }
        archiveArtifacts artifacts: 'boot_log.txt, test_results.txt', fingerprint: true
    }
}

    }
}

      